./main ../instanciasPRPP/CHRISTOFIDES/P01NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P02NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P03NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P04NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P05NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P06NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P07NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P08NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P09NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P10NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P11NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P12NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P13NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P14NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P15NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P16NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P17NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P18NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P19NoRPP
./main ../instanciasPRPP/CHRISTOFIDES/P20NoRPP
./main ../instanciasPRPP/DEGREE/D0NoRPP
./main ../instanciasPRPP/DEGREE/D1NoRPP
./main ../instanciasPRPP/DEGREE/D2NoRPP
./main ../instanciasPRPP/DEGREE/D3NoRPP
./main ../instanciasPRPP/DEGREE/D4NoRPP
./main ../instanciasPRPP/DEGREE/D5NoRPP
./main ../instanciasPRPP/DEGREE/D6NoRPP
./main ../instanciasPRPP/DEGREE/D7NoRPP
./main ../instanciasPRPP/DEGREE/D8NoRPP
./main ../instanciasPRPP/DEGREE/D9NoRPP
./main ../instanciasPRPP/DEGREE/D10NoRPP
./main ../instanciasPRPP/DEGREE/D11NoRPP
./main ../instanciasPRPP/DEGREE/D12NoRPP
./main ../instanciasPRPP/DEGREE/D13NoRPP
./main ../instanciasPRPP/DEGREE/D14NoRPP
./main ../instanciasPRPP/GRID/G0NoRPP
./main ../instanciasPRPP/GRID/G1NoRPP
./main ../instanciasPRPP/GRID/G2NoRPP
./main ../instanciasPRPP/GRID/G3NoRPP
./main ../instanciasPRPP/GRID/G4NoRPP
./main ../instanciasPRPP/GRID/G5NoRPP
./main ../instanciasPRPP/GRID/G6NoRPP
./main ../instanciasPRPP/GRID/G7NoRPP
./main ../instanciasPRPP/GRID/G8NoRPP
./main ../instanciasPRPP/GRID/G9NoRPP
./main ../instanciasPRPP/GRID/G10NoRPP
./main ../instanciasPRPP/GRID/G11NoRPP
./main ../instanciasPRPP/GRID/G12NoRPP
./main ../instanciasPRPP/GRID/G13NoRPP
./main ../instanciasPRPP/GRID/G14NoRPP
./main ../instanciasPRPP/GRID/G15NoRPP
./main ../instanciasPRPP/RANDOM/R0NoRPP
./main ../instanciasPRPP/RANDOM/R1NoRPP
./main ../instanciasPRPP/RANDOM/R2NoRPP
./main ../instanciasPRPP/RANDOM/R3NoRPP
./main ../instanciasPRPP/RANDOM/R4NoRPP
./main ../instanciasPRPP/RANDOM/R5NoRPP
./main ../instanciasPRPP/RANDOM/R6NoRPP
./main ../instanciasPRPP/RANDOM/R7NoRPP
./main ../instanciasPRPP/RANDOM/R8NoRPP
./main ../instanciasPRPP/RANDOM/R9NoRPP
./main ../instanciasPRPP/RANDOM/R10NoRPP
